# Generated by Django 5.0.6 on 2024-06-02 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flask_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankedProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductNameType', models.CharField(max_length=255)),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_count', models.IntegerField()),
                ('recipe_id', models.IntegerField()),
            ],
            options={
                'db_table': 'RankedProductPrices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Specials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=255)),
                ('ProductNameType', models.CharField(max_length=255)),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DishName', models.CharField(max_length=255)),
                ('DishType', models.CharField(max_length=255)),
                ('DishSort', models.CharField(max_length=255)),
                ('DishTime', models.CharField(max_length=255)),
                ('ProductOtherProducts', models.TextField()),
                ('Description', models.TextField()),
                ('Machinery', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
