# Generated by Django 5.0.6 on 2024-06-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flask_app', '0002_rankedproductprice_specials_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankedProductPricess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductNameType', models.CharField(max_length=255)),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_count', models.IntegerField()),
                ('recipe_id', models.IntegerField()),
            ],
            options={
                'db_table': 'RankedProductPrices',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='RankedProductPrice',
        ),
    ]
