# Generated by Django 5.0.6 on 2024-06-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flask_app', '0003_rankedproductpricess_delete_rankedproductprice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rankedproductpricess',
            table='RankedProductPricesss',
        ),
    ]
