# Generated by Django 5.0.6 on 2024-06-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flask_app', '0004_alter_rankedproductpricess_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rankedproductpricess',
            table='RankedPr',
        ),
    ]
