# Generated by Django 5.0.6 on 2024-06-08 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flask_app', '0007_alter_rankedproductpricess_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rankedproductpricess',
            table='rankedproductstable',
        ),
    ]
