# Generated by Django 5.0.6 on 2024-06-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flask_app', '0008_alter_rankedproductpricess_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rankedproductpricess',
            table='rankedpr',
        ),
    ]
