# Generated by Django 5.0.6 on 2024-06-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flask_app', '0010_alter_rankedproductpricess_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='specials',
            name='ProductOwner',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
