# Generated by Django 5.0.6 on 2024-07-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flask_app', '0013_remove_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(upload_to='recipes/'),
        ),
    ]
